/**
 * Ensure a VFS stub exists so the regular (non-native) build can resolve
 * the import in skill-source.ts. The real VFS is generated by generate-vfs.ts
 * during build:native and overwrites this stub.
 */
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';

const dir = join(import.meta.dir, '..', 'src', 'cli', 'generated');
const file = join(dir, 'skills-vfs.ts');

if (!existsSync(file)) {
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    file,
    `// Auto-generated stub — replaced by generate-vfs.ts during native build\nexport const SKILLS_VFS = new Map();\nexport const SKILL_NAMES: string[] = [];\n`
  );
  console.log('Created VFS stub:', file);
}
